language: php
php:
  - "7.2"
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
          - travis encrypt --add deploy.api_key d1d49dcb-d92e-4be5-8105-68129f0952e8
        script: bash .bin/deploy.sh
        after_script: skip
install:
  - travis_retry composer require --dev $COMPOSER_ARGS
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
