language: php
php:
  - 7.2
jobs:
  include:
    - stage: release
      deploy:
        if: tag IS present AND type = push
        provider: script
        file: wirecardpaymentgateway.zip
        skip_cleanup: true
        before_script:
          - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
        script:
          - bash .bin/generate-release-package.sh
          - bash .bin/deploy.sh
        after_script: skip
install:
  - travis_retry composer require --dev $COMPOSER_ARGS
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
