sudo: false
dist: trusty
language: php

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
  - PRESTASHOP_RELEASES_FILE=${TRAVIS_BUILD_DIR}/.bin/shop-releases.txt

matrix:
  allow_failures:
    - stage: acceptance-test
  include:
  - php: 5.6
    if: env(PHRASEAPP_PULL) != '1' AND type != cron
  - php: 7.0
    if: env(PHRASEAPP_PULL) != '1' AND type != cron
  - php: 7.1
    if: env(PHRASEAPP_PULL) != '1' AND type != cron

  - stage: validator-test
    if: env(VALIDATOR_TEST) = '1'
    php: 7.1
    before_script:
      - pip install --user bs4
      - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
    script:
      - bash .bin/run-validator-test.sh
    after_script: skip

  - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script: bash .bin/deploy.sh

install:
  - travis_retry composer require --dev $COMPOSER_ARGS
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
script:
  - composer test-coverage
  - composer cs-check

after_script:
  - travis_retry composer upload-coverage
  - bash .bin/generate-tag.sh
